### ISSUE TITLE
Issue with INI example

### ISSUE THREAD

**Issue by TabulateJarl8** [alecthomas/participle#246]
Hi. I was trying out this library, and I figured a good way to start would be to try and add something to an existing example. I decided on the INI example since it's pretty basic, but once I pasted it into my file and tried to build it, I got an error. I'm new to go so I'm not entirely sure what to do, but the error that I get is `./main.go:26:14: undefined: participle.Union`. Is the example outdated or something? Thanks for the help

**Comment by billgraziano** [comment]
I am having the same problem

**Comment by billgraziano** [comment]
I'm not sure what the state of this library is.  Is it usable?  I copied that tutorial code, and I can't get it to work with 0.7.1 or v2.

**Comment by TabulateJarl8** [comment]
I wasn't sure if I wanted to use a module who's basic example didn't work, so I did some research into alternatives. This probably won't work for everyone's use case, but I think I'm gonna go with [ANTLR](https://github.com/antlr/antlr4) instead.

**Comment by alecthomas** [comment]
It works fine. You have to run it from the _examples directory, as it has its own module.

**Comment by alecthomas** [comment]
And it won't work with 0.7 because it uses the v2 API.

**Comment by alecthomas** [comment]
Looks like I messed up the versioning by thinking that `alpha11` would be after `alpha9`. I've corrected this by releasing `v2.0.0-beta.1`
